### ISSUE TITLE
All tars are broken

### ISSUE THREAD

**Issue by nilleiz** [escomputers/freepbx-docker#22]
All the archives in the source folder are not extractable, so this repo is basically unusable.

**Comment by escomputers** [comment]
First of all, I don't appreciate the tone conveyed by your words, as if it were more of a complaint that I should immediately resolve rather than an "issue" on an open-source repository!

That being said, the tar files you're referring to are only necessary if you want to build the image from scratch. However, the problem causing the corruption of these tar files is due to Git when pushing the changes made. I tried to resolve it (as you might have noticed if you read the commits) by adding *.tar.gz binary to the .gitattributes file, but apparently, it didn't work.

Unfortunately, I don't have the time at the moment to further investigate the issue.
